---
- name: Deploy Webservices
  hosts: octoprint
  user: "{{ ansible_ssh_user }}"
  become: True
  roles:
    - role: nleiva.grafana_agent
      vars:
        grafana_api_key: '{{ lookup("env", "GRAFANA_API_KEY") }}'
        prometheus_user: '{{ lookup("env", "PROMETHEUS_USER") | int}}'
        loki_user: '{{ lookup("env", "LOKI_USER") | int }}'
        grafana_location_prometheus: prod-01-eu-west-0
        grafana_location_promtail: eu-west-0
