---
- name: Download latest Promtail release
  ansible.builtin.get_url:
    url: "https://github.com/grafana/loki/releases/latest/download/promtail-linux-{{ promtail_type[ansible_architecture] }}.zip"
    dest: "/tmp/promtail-linux.zip"
    mode: "0644"

- name: Create directory for Promtail's files
  ansible.builtin.file:
    state: directory
    recurse: true
    path: "{{ promtail_location }}"
    mode: u=rwX,g=rX,o=rX

- name: Unarchive Promtail
  ansible.builtin.unarchive:
    src: "/tmp/promtail-linux.zip"
    dest: "{{ promtail_location }}"
    remote_src: true
    mode: "0755"

- name: Create an Promtail config file
  ansible.builtin.template:
    src: "{{ grafana_promtail_config_template }}"
    dest: "{{ promtail_location }}/promtail-config.yaml"
    mode: u=rw,g=r,o=r
    force: true
  notify: Reload Promtail service

- name: Create Systemd service
  block:
    - name: Template the new service file for Promtail agent
      ansible.builtin.template:
        src: "{{ grafana_promtail_systemd_template }}"
        dest: "{{ systemd_service_folder }}/promtail.service"
        mode: "0644"
      notify: Reload Promtail service

    - name: Reload and start service Promtail agent
      ansible.builtin.service:
        name: promtail
        state: started
        enabled: true
