---
- name: Reload Grafana agent service
  ansible.builtin.service:
    name: grafana-agent
    state: restarted
    daemon_reload: true

- name: Reload Promtail service
  ansible.builtin.service:
    name: promtail
    state: restarted
    daemon_reload: true
